cookie:
  expiry_days: 7
  key: f?/;4-XAu*{nrTL:B`h^m(t6M@+}Y&
  name: reauth_code
credentials:
  usernames:
    aadmin:
      email: admin@example.com
      failed_login_attempts: 0
      first_name: Adminero
      last_name: Adminini
      logged_in: true
      password: $2b$12$glS/XQRA5uWP.iLFxkicn.llJ1sZxTd6dXG.2.Gxer3Pn0znmUC6a
      roles:
      - admin
      - editor
      - viewer
    mmustermann:
      email: m.mustermann@example.com
      failed_login_attempts: 0
      first_name: Max
      last_name: Mustermann
      logged_in: false
      password: $2b$12$TBySPY0FYXdzLZKuzC3bL.ZqpDroxs5mRPR8L2O4vCJtQlbq0Uk.q
      roles:
      - viewer
