from enum import Enum


class EnvConfig(Enum):
    ENVIRONMENT = "ENVIRONMENT"
    API_BASE_URL = "API_BASE_URL"
    API_TOKEN = "API_TOKEN"
    AUTH_CONFIG_FILE = "AUTH_CONFIG_FILE"
    OTEL_SERVICE_NAME = "OTEL_SERVICE_NAME"
    OTEL_EXPORTER_OTLP_ENDPOINT = "OTEL_EXPORTER_OTLP_ENDPOINT"
    OTEL_LOG_LEVEL = "OTEL_LOG_LEVEL"
