name: test-app

on:
  push:
    branches:
    - frontend-streamlit

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: ./app/

    strategy:
      matrix:
        python-version: [3.12]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Test App Code
        run: poetry run python -m pytest tests

 
          
      
      
      


