name: CD Pipeline for Docker

on:
  push:
    branches:
      - frontend-streamlit

jobs:
  publish:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          export IMAGE_TAG=ghcr.io/fhswf-study-projects/mlops-project:${{ github.sha }}
          docker compose build tag ghcr.io/fhswf-study-projects/mlops-project:latest $IMAGE_TAG
          docker push ghcr.io/fhswf-study-projects/mlops-project:latest
          docker push $IMAGE_TAG
