name: CI Pipeline for the app

on:
  push:
    branches:
      - frontend-streamlit
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      poetry-cache: ${{ steps.cache-poetry.outputs.cache-hit }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Poetry & Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
        working-directory: ./app

  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Tests
        run: poetry run pytest -v --disable-warnings tests
        working-directory: ./app

  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Ruff Linting
        run: poetry run ruff check --fix .
        working-directory: ./app

  typecheck:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Type Checking
        run: poetry run pyright .
        working-directory: ./app
