name: CI CD Pipeline

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci.yml
    secrets: inherit

  cd:
    name: CD
    needs: ci
    uses: ./.github/workflows/publish.yml
    secrets: inherit
