[logger]
level = "error"
messageFormat = "%(asctime)s %(levelname) -7s %(name)s: %(message)s"

[browser]
gatherUsageStats = false

[server]
headless = true
address = "0.0.0.0"
enableCORS = true
enableXsrfProtection = false
